spring.datasource.url=jdbc:postgresql://localhost:5432/state_db
spring.datasource.username=postgres
spring.datasource.password=2809

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properti es.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect